package scb.recontool.txn;

public enum TxnError {
	TXN_LINE_EMPTY, 
	TXN_ATTRIBUTE_INCOMPLETE, 
	POSTING_DATE_ERROR, 
	AMOUNT_MORE_THAN_2_SCALE, 
	AMOUNT_ATTRIBUTE_INCORRECT, 
	GENERIC_ERROR,
	POSTING_DATE_INVALID_ERROR ;

}
